// Generated by the OpenNext build.
// @ts-ignore
import { default as openNextHandler } from './.open-next/worker.js'
import { purgeExpiredChatData } from './lib/chat/repository'
import { CHAT_LIMITS } from './lib/chat/limits'
import { handleRealtimeRequest } from './lib/chat/realtime-http'
import { isScannerPath } from './lib/scanner-path'

const MAX_PURGE_BATCHES_PER_RUN = 10

function isExplicitlyCacheable(request: Request, response: Response) {
  const url = new URL(request.url)
  const contentType = response.headers.get('content-type') ?? ''

  return (
    (request.method === 'GET' || request.method === 'HEAD') &&
    url.pathname.startsWith('/media/') &&
    response.status === 200 &&
    contentType.toLowerCase().startsWith('image/') &&
    !response.headers.has('set-cookie')
  )
}

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url)

    if (isScannerPath(url.pathname)) {
      return new Response('Not found', {
        status: 404,
        headers: {
          'Cache-Control': 'no-store',
          'Content-Type': 'text/plain; charset=utf-8',
          'X-Content-Type-Options': 'nosniff',
        },
      })
    }

    // OpenNext's Node response adapter cannot construct a 101 upgrade. Route
    // realtime requests directly so the platform WebSocket handle survives.
    const realtimeResponse = await handleRealtimeRequest(request, env)
    if (realtimeResponse) return realtimeResponse

    const response = await openNextHandler.fetch(request, env, ctx)

    // A WebSocket upgrade response must keep its platform WebSocket handle.
    // Re-wrapping it below would turn the 101 into a normal Response and drop
    // the connection before it reaches the browser.
    if (response.webSocket) {
      return response
    }

    if (isExplicitlyCacheable(request, response)) {
      return response
    }

    const headers = new Headers(response.headers)
    headers.set('Cache-Control', 'private, no-store, max-age=0')
    headers.set('CDN-Cache-Control', 'no-store')
    headers.set('Cloudflare-CDN-Cache-Control', 'no-store')

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    })
  },

  async scheduled(controller: ScheduledController, env: CloudflareEnv) {
    if (controller.cron !== CHAT_LIMITS.cleanupCron) return

    for (let batch = 0; batch < MAX_PURGE_BATCHES_PER_RUN; batch += 1) {
      const result = await purgeExpiredChatData(env.CHAT_DB)
      if (result.conversations < CHAT_LIMITS.purgeBatchSize) break
    }
  },
} satisfies ExportedHandler<CloudflareEnv>

// Generated by the OpenNext build.
// @ts-ignore
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js'
export { ChatConversation } from './lib/chat/realtime-object'
