// Generated by the OpenNext build.
// @ts-ignore
import { default as openNextHandler } from './.open-next/worker.js'
import { purgeExpiredChatData } from './lib/chat/db'
import { CHAT_LIMITS } from './lib/chat/limits'

const MAX_PURGE_BATCHES_PER_RUN = 10

function isExplicitlyCacheable(request: Request, response: Response) {
  const url = new URL(request.url)
  const contentType = response.headers.get('content-type') ?? ''

  return (
    (request.method === 'GET' || request.method === 'HEAD') &&
    url.pathname.startsWith('/media/') &&
    response.status === 200 &&
    contentType.toLowerCase().startsWith('image/') &&
    !response.headers.has('set-cookie')
  )
}

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const response = await openNextHandler.fetch(request, env, ctx)

    if (isExplicitlyCacheable(request, response)) {
      return response
    }

    const headers = new Headers(response.headers)
    headers.set('Cache-Control', 'private, no-store, max-age=0')
    headers.set('CDN-Cache-Control', 'no-store')
    headers.set('Cloudflare-CDN-Cache-Control', 'no-store')

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    })
  },

  async scheduled(controller: ScheduledController, env: CloudflareEnv) {
    if (controller.cron !== CHAT_LIMITS.cleanupCron) return

    for (let batch = 0; batch < MAX_PURGE_BATCHES_PER_RUN; batch += 1) {
      const result = await purgeExpiredChatData(env.CHAT_DB)
      // 消息和会话两个子查询的批次可能不一致：只要任一删满一批就继续，
      // 否则积压时（如消息多于会话）会提前退出导致清理永远追不上。
      if (
        result.messages < CHAT_LIMITS.purgeBatchSize &&
        result.conversations < CHAT_LIMITS.purgeBatchSize
      )
        break
    }
  },
} satisfies ExportedHandler<CloudflareEnv>

// Generated by the OpenNext build.
// @ts-ignore
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js'
