// Generated by the OpenNext build.
// @ts-ignore
import { default as openNextHandler } from './.open-next/worker.js'
import { purgeExpiredChatData } from './lib/chat/db'
import { CHAT_LIMITS } from './lib/chat/limits'

const MAX_PURGE_BATCHES_PER_RUN = 10

export default {
  fetch: openNextHandler.fetch,

  async scheduled(controller: ScheduledController, env: CloudflareEnv) {
    if (controller.cron !== CHAT_LIMITS.cleanupCron) return

    for (let batch = 0; batch < MAX_PURGE_BATCHES_PER_RUN; batch += 1) {
      const result = await purgeExpiredChatData(env.CHAT_DB)
      if (result.conversations < CHAT_LIMITS.purgeBatchSize) break
    }
  },
} satisfies ExportedHandler<CloudflareEnv>

// Generated by the OpenNext build.
// @ts-ignore
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js'
