version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: solidays-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: solidays123
      MYSQL_DATABASE: solidays_db
      MYSQL_USER: solidays
      MYSQL_PASSWORD: solidays123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - blog-network
    command: --default-authentication-plugin=mysql_native_password

  # Next.js 前端应用
  solidays-frontend:
    image: ccr.ccs.tencentyun.com/solidays/solidays:frontend
    container_name: solidays-frontend
    ports:
      - "80:3000"
    restart: unless-stopped
    depends_on:
      - mysql
      - solidays-backend
    networks:
      - blog-network

  # Python 后端应用
  solidays-backend:
    image: ccr.ccs.tencentyun.com/solidays/solidays:backend
    container_name: solidays-backend
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=mysql://solidays:solidays123@mysql:3306/solidays_db
      - FLASK_ENV=production
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - blog-network
volumes:
  mysql_data:
    driver: local

networks:
  blog-network:
    driver: bridge
